{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nats-kms-auth.fullname" . }}
  labels: {{- include "nats-kms-auth.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
{{- end }}
