apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats-kms-auth.fullname" . }}
  labels: {{- include "nats-kms-auth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "nats-kms-auth.selectorLabels" . | nindent 4 }}
