{{- if .Values.generate.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nats-aws-auth.generate.fullname" . }}
  labels: {{- include "nats-aws-auth.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": {{ .Values.generate.hookDeletePolicy }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nats-aws-auth.generate.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nats-aws-auth.generate.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
