{{- if .Values.generate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nats-aws-auth.generate.serviceAccountName" . }}
  labels: {{- include "nats-aws-auth.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": {{ .Values.generate.hookDeletePolicy }}
    {{- with .Values.generate.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
